-- MySQL Script generated by MySQL Workbench
-- Tue May 20 00:25:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `correro` VARCHAR(45) NOT NULL UNIQUE,
  `usuario` VARCHAR(45) NOT NULL UNIQUE,
  `contrasena` VARCHAR(255) NOT NULL UNIQUE,
  `notificacion` ENUM('off', 'on') NOT NULL DEFAULT 'on',
  `logo` MEDIUMBLOB NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_na` VARCHAR(45) NOT NULL,
  `correro` VARCHAR(45) NOT NULL UNIQUE,
  `usuario` VARCHAR(45) NOT NULL UNIQUE,
  `contrasena` VARCHAR(255) NOT NULL UNIQUE,
  `notificacion` ENUM('off', 'on') NOT NULL DEFAULT 'on',
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`perfil_solicitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil_solicitado` (
  `idempresa` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `requerimiento` VARCHAR(45) NOT NULL,
  `contrato` VARCHAR(45) NOT NULL,
  `hora_laborales` VARCHAR(45) NOT NULL,
  `salario` FLOAT NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idempresa`, `idusuario`),
  CONSTRAINT `fk_perfil_solicitado_empresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `mydb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_solicitado_Usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`CV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CV` (
  `idcv` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `archivo` MEDIUMBLOB NOT NULL,
  `tipo_archivo` VARCHAR(10) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcv`, `idusuario`),
  CONSTRAINT `fk_CV_Usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `iddireccion` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `idusuario` INT NOT NULL,
  `idempresa` INT NOT NULL,
  PRIMARY KEY (`iddireccion`, `idusuario`, `idempresa`),
  CONSTRAINT `fk_direccion_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `mydb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_Usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefono` (
  `idtelefono` INT NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idtelefono`, `idusuario`),
  CONSTRAINT `fk_telefono_Usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;






-- Crear una nueva tabla específica para ofertas de trabajo
CREATE TABLE IF NOT EXISTS `mydb`.`ofertas_trabajo` (
  `idoferta` INT NOT NULL AUTO_INCREMENT,
  `idempresa` INT NOT NULL,
  `puesto` VARCHAR(100) NOT NULL,
  `lugar` VARCHAR(100) NOT NULL,
  `requerimiento` TEXT NOT NULL,
  `contrato` VARCHAR(50) NOT NULL,
  `hora_laborales` VARCHAR(50) NOT NULL,
  `salario` FLOAT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `activa` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`idoferta`),
  CONSTRAINT `fk_ofertas_empresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `mydb`.`empresa` (`idempresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;




-- Opcional: Crear tabla para relacionar aplicaciones de usuarios a ofertas
CREATE TABLE IF NOT EXISTS `mydb`.`aplicaciones` (
  `idaplicacion` INT NOT NULL AUTO_INCREMENT,
  `idoferta` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `fecha_aplicacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente', 'revisando', 'aceptada', 'rechazada') DEFAULT 'pendiente',
  PRIMARY KEY (`idaplicacion`),
  UNIQUE KEY `unique_aplicacion` (`idoferta`, `idusuario`),
  CONSTRAINT `fk_aplicaciones_oferta`
    FOREIGN KEY (`idoferta`)
    REFERENCES `mydb`.`ofertas_trabajo` (`idoferta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aplicaciones_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
